{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.nucleuspowered",
    "module": "neutrino",
    "version": "1.1.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "3.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "neutrino-1.1.7-SNAPSHOT.jar",
          "url": "neutrino-1.1.7-SNAPSHOT.jar",
          "size": 34546,
          "sha512": "4cde7ae1dfbf60d75bc828f8a78be5ed1a9cf32de2ac40fa6f6aa3647688e62b7ab984e2c411b94c2a364cb919e7432d926ab785a0172d8f8d83d74aaeefdb91",
          "sha256": "6ff1a34cf8650bf33cbb83cf2bad3880938b4a97119b3e9704299179de457ba1",
          "sha1": "c726b2275db23af09ad2c5cc617f6addf1ab869e",
          "md5": "91822414dcd2024be1100755937ce9de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "3.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "neutrino-1.1.7-SNAPSHOT.jar",
          "url": "neutrino-1.1.7-SNAPSHOT.jar",
          "size": 34546,
          "sha512": "4cde7ae1dfbf60d75bc828f8a78be5ed1a9cf32de2ac40fa6f6aa3647688e62b7ab984e2c411b94c2a364cb919e7432d926ab785a0172d8f8d83d74aaeefdb91",
          "sha256": "6ff1a34cf8650bf33cbb83cf2bad3880938b4a97119b3e9704299179de457ba1",
          "sha1": "c726b2275db23af09ad2c5cc617f6addf1ab869e",
          "md5": "91822414dcd2024be1100755937ce9de"
        }
      ]
    }
  ]
}
